//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RFS.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfilePic
    {
        public string Id { get; set; }
        public string UserId { get; set; }
        public byte[] data { get; set; }
        public string ext { get; set; }
    
        public virtual user user { get; set; }
    }
}
