//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Room()
        {
            this.RoomProfilePics = new HashSet<RoomProfilePic>();
        }
    
        public string Id { get; set; }
        public string RoomName { get; set; }
        public bool Projector { get; set; }
        public int Sitting { get; set; }
        public string location { get; set; }
        public bool VideoConferencing_ { get; set; }
        public bool MonitorScreen { get; set; }
        public Nullable<bool> decommission { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoomProfilePic> RoomProfilePics { get; set; }
    }
}
